// prayer-data.js — Catholic Prayer Translator data
// All translations are standard liturgical texts used at Mass and in official prayer books.

window.LANG_NAMES = {
  en: 'English', la: 'Latin', es: 'Español', fr: 'Français',
  it: 'Italiano', de: 'Deutsch', pt: 'Português', pl: 'Polski'
};

window.PRAYER_CATEGORIES = [
  { id: 'basic',     label: 'Basic Prayers',   prayers: ['ourFather','hailMary','gloryBe'] },
  { id: 'creed',     label: 'Creeds',           prayers: ['apostlesCreed','niceneCreed'] },
  { id: 'mass',      label: 'Holy Mass',        prayers: ['confiteor','kyrie','gloria','sanctus','agnus'] },
  { id: 'marian',   label: 'Marian Prayers',   prayers: ['salveRegina','reginaCaeli','memorare','subTuum'] },
  { id: 'devotional',label: 'Devotional',       prayers: ['animaChristi','angelus','actContrition'] },
];

window.PRAYERS = [

// ─── BASIC PRAYERS ──────────────────────────────────────────

{
  id: 'ourFather',
  title: { en:"Our Father", la:"Pater Noster", es:"Padre Nuestro", fr:"Notre Père", it:"Padre Nostro", de:"Vater Unser", pt:"Pai Nosso", pl:"Ojcze Nasz" },
  verses: [
    { en:"Our Father, who art in heaven,", la:"Pater noster, qui es in caelis,", es:"Padre nuestro, que estás en el cielo,", fr:"Notre Père, qui es aux cieux,", it:"Padre nostro, che sei nei cieli,", de:"Vater unser im Himmel,", pt:"Pai nosso que estais no céu,", pl:"Ojcze nasz, któryś jest w niebie," },
    { en:"hallowed be thy name.", la:"sanctificetur nomen tuum.", es:"santificado sea tu nombre.", fr:"que ton nom soit sanctifié,", it:"sia santificato il tuo nome,", de:"geheiligt werde dein Name;", pt:"santificado seja o vosso nome;", pl:"święć się imię Twoje;" },
    { en:"Thy kingdom come,", la:"Adveniat regnum tuum,", es:"venga a nosotros tu reino,", fr:"que ton règne vienne,", it:"venga il tuo regno,", de:"dein Reich komme;", pt:"venha a nós o vosso reino;", pl:"przyjdź królestwo Twoje;" },
    { en:"thy will be done,", la:"fiat voluntas tua,", es:"hágase tu voluntad", fr:"que ta volonté soit faite", it:"sia fatta la tua volontà,", de:"dein Wille geschehe", pt:"seja feita a vossa vontade", pl:"bądź wola Twoja" },
    { en:"on earth as it is in heaven.", la:"sicut in caelo et in terra.", es:"en la tierra como en el cielo.", fr:"sur la terre comme au ciel.", it:"come in cielo così in terra.", de:"wie im Himmel so auf Erden.", pt:"assim na terra como no céu.", pl:"jako w niebie tak i na ziemi." },
    { en:"Give us this day our daily bread,", la:"Panem nostrum quotidianum da nobis hodie,", es:"Danos hoy nuestro pan de cada día;", fr:"Donne-nous aujourd'hui notre pain de ce jour;", it:"Dacci oggi il nostro pane quotidiano,", de:"Unser tägliches Brot gib uns heute;", pt:"o pão nosso de cada dia nos dai hoje;", pl:"chleba naszego powszedniego daj nam dzisiaj;" },
    { en:"and forgive us our trespasses,", la:"et dimitte nobis debita nostra,", es:"y perdona nuestras ofensas,", fr:"pardonne-nous nos offenses,", it:"e rimetti a noi i nostri debiti", de:"und vergib uns unsere Schuld,", pt:"perdoai-nos as nossas ofensas,", pl:"i przebacz nam nasze winy," },
    { en:"as we forgive those who trespass against us.", la:"sicut et nos dimittimus debitoribus nostris.", es:"como también nosotros perdonamos a los que nos ofenden.", fr:"comme nous pardonnons aussi à ceux qui nous ont offensés.", it:"come noi li rimettiamo ai nostri debitori,", de:"wie auch wir vergeben unsern Schuldigern;", pt:"assim como nós perdoamos a quem nos tem ofendido;", pl:"jako i my przebaczamy naszym winowajcom;" },
    { en:"And lead us not into temptation,", la:"Et ne nos inducas in tentationem,", es:"y no nos dejes caer en la tentación,", fr:"et ne nous soumets pas à la tentation,", it:"e non ci indurre in tentazione,", de:"und führe uns nicht in Versuchung,", pt:"e não nos deixeis cair em tentação,", pl:"i nie wódź nas na pokuszenie," },
    { en:"but deliver us from evil.", la:"sed libera nos a malo.", es:"sino líbranos del mal.", fr:"mais délivre-nous du Mal.", it:"ma liberaci dal male.", de:"sondern erlöse uns von dem Bösen.", pt:"mas livrai-nos do mal.", pl:"ale nas zbaw ode złego." },
    { en:"Amen.", la:"Amen.", es:"Amén.", fr:"Amen.", it:"Amen.", de:"Amen.", pt:"Amém.", pl:"Amen." },
  ]
},

{
  id: 'hailMary',
  title: { en:"Hail Mary", la:"Ave Maria", es:"Dios te Salve", fr:"Je vous salue Marie", it:"Ave Maria", de:"Gegrüßet seist du", pt:"Ave Maria", pl:"Zdrowaś Maryjo" },
  verses: [
    { en:"Hail Mary, full of grace,", la:"Ave Maria, gratia plena,", es:"Dios te salve, María, llena eres de gracia,", fr:"Je vous salue, Marie, pleine de grâce,", it:"Ave, o Maria, piena di grazia,", de:"Gegrüßet seist du, Maria, voll der Gnade,", pt:"Ave Maria, cheia de graça,", pl:"Zdrowaś Maryjo, łaski pełna," },
    { en:"the Lord is with thee.", la:"Dominus tecum.", es:"el Señor es contigo.", fr:"le Seigneur est avec vous.", it:"il Signore è con te.", de:"der Herr ist mit dir.", pt:"o Senhor é convosco;", pl:"Pan z Tobą," },
    { en:"Blessed art thou among women,", la:"Benedicta tu in mulieribus,", es:"Bendita tú eres entre todas las mujeres,", fr:"Vous êtes bénie entre toutes les femmes,", it:"tu sei benedetta fra le donne", de:"du bist gebenedeit unter den Frauen,", pt:"bendita sois vós entre as mulheres,", pl:"błogosławionaś Ty między niewiastami," },
    { en:"and blessed is the fruit of thy womb, Jesus.", la:"et benedictus fructus ventris tui, Iesus.", es:"y bendito es el fruto de tu vientre, Jesús.", fr:"et Jésus, le fruit de vos entrailles, est béni.", it:"e benedetto è il frutto del tuo seno, Gesù.", de:"und gebenedeit ist die Frucht deines Leibes, Jesus.", pt:"e bendito é o fruto do vosso ventre, Jesus.", pl:"i błogosławiony owoc żywota Twojego, Jezus." },
    { en:"Holy Mary, Mother of God,", la:"Sancta Maria, Mater Dei,", es:"Santa María, Madre de Dios,", fr:"Sainte Marie, Mère de Dieu,", it:"Santa Maria, Madre di Dio,", de:"Heilige Maria, Mutter Gottes,", pt:"Santa Maria, Mãe de Deus,", pl:"Święta Maryjo, Matko Boża," },
    { en:"pray for us sinners,", la:"ora pro nobis peccatoribus,", es:"ruega por nosotros pecadores,", fr:"priez pour nous, pauvres pécheurs,", it:"prega per noi peccatori,", de:"bitte für uns Sünder", pt:"rogai por nós, pecadores,", pl:"módl się za nami grzesznymi," },
    { en:"now and at the hour of our death.", la:"nunc et in hora mortis nostrae.", es:"ahora y en la hora de nuestra muerte.", fr:"maintenant et à l'heure de notre mort.", it:"adesso e nell'ora della nostra morte.", de:"jetzt und in der Stunde unseres Todes.", pt:"agora e na hora da nossa morte.", pl:"teraz i w godzinę śmierci naszej." },
    { en:"Amen.", la:"Amen.", es:"Amén.", fr:"Amen.", it:"Amen.", de:"Amen.", pt:"Amém.", pl:"Amen." },
  ]
},

{
  id: 'gloryBe',
  title: { en:"Glory Be", la:"Gloria Patri", es:"Gloria al Padre", fr:"Gloire soit au Père", it:"Gloria al Padre", de:"Ehre sei dem Vater", pt:"Glória ao Pai", pl:"Chwała Ojcu" },
  verses: [
    { en:"Glory be to the Father,", la:"Gloria Patri,", es:"Gloria al Padre,", fr:"Gloire soit au Père,", it:"Gloria al Padre,", de:"Ehre sei dem Vater", pt:"Glória ao Pai,", pl:"Chwała Ojcu" },
    { en:"and to the Son,", la:"et Filio,", es:"y al Hijo,", fr:"et au Fils,", it:"e al Figlio,", de:"und dem Sohn", pt:"e ao Filho,", pl:"i Synowi," },
    { en:"and to the Holy Spirit.", la:"et Spiritui Sancto.", es:"y al Espíritu Santo.", fr:"et au Saint-Esprit,", it:"e allo Spirito Santo.", de:"und dem Heiligen Geist.", pt:"e ao Espírito Santo,", pl:"i Duchowi Świętemu." },
    { en:"As it was in the beginning,", la:"Sicut erat in principio,", es:"Como era en el principio,", fr:"Comme il était au commencement,", it:"Come era in principio,", de:"Wie es war im Anfang,", pt:"Como era no princípio,", pl:"Jak było na początku," },
    { en:"is now, and ever shall be,", la:"et nunc et semper,", es:"ahora y siempre,", fr:"maintenant et toujours,", it:"ora e sempre,", de:"so auch jetzt und alle Zeit,", pt:"assim agora e sempre,", pl:"teraz i zawsze," },
    { en:"world without end.", la:"et in saecula saeculorum.", es:"por los siglos de los siglos.", fr:"dans les siècles des siècles.", it:"nei secoli dei secoli.", de:"und in Ewigkeit.", pt:"e pelos séculos dos séculos.", pl:"i na wieki wieków." },
    { en:"Amen.", la:"Amen.", es:"Amén.", fr:"Amen.", it:"Amen.", de:"Amen.", pt:"Amém.", pl:"Amen." },
  ]
},

// ─── CREEDS ─────────────────────────────────────────────────

{
  id: 'apostlesCreed',
  title: { en:"Apostles' Creed", la:"Symbolum Apostolorum", es:"Credo Apostólico", fr:"Symbole des Apôtres", it:"Credo Apostolico", de:"Apostolisches Glaubensbekenntnis", pt:"Credo dos Apóstolos", pl:"Skład Apostolski" },
  verses: [
    { en:"I believe in God, the Father Almighty,", la:"Credo in Deum Patrem omnipotentem,", es:"Creo en Dios, Padre todopoderoso,", fr:"Je crois en Dieu, le Père tout-puissant,", it:"Credo in Dio, Padre onnipotente,", de:"Ich glaube an Gott, den Vater, den Allmächtigen,", pt:"Creio em Deus Pai todo-poderoso,", pl:"Wierzę w Boga, Ojca wszechmogącego," },
    { en:"Creator of heaven and earth.", la:"Creatorem caeli et terrae.", es:"Creador del cielo y de la tierra.", fr:"Créateur du ciel et de la terre.", it:"creatore del cielo e della terra.", de:"den Schöpfer des Himmels und der Erde.", pt:"criador do céu e da terra.", pl:"Stworzyciela nieba i ziemi." },
    { en:"I believe in Jesus Christ, his only Son, our Lord,", la:"Et in Iesum Christum, Filium eius unicum, Dominum nostrum,", es:"Creo en Jesucristo, su único Hijo, nuestro Señor,", fr:"Je crois en Jésus-Christ, son Fils unique, notre Seigneur,", it:"Credo in Gesù Cristo, suo unico Figlio, nostro Signore,", de:"und an Jesus Christus, seinen eingeborenen Sohn, unsern Herrn,", pt:"e em Jesus Cristo, seu único Filho, nosso Senhor,", pl:"i w Jezusa Chrystusa, Syna Jego jedynego, Pana naszego," },
    { en:"who was conceived by the Holy Spirit,", la:"qui conceptus est de Spiritu Sancto,", es:"que fue concebido por obra y gracia del Espíritu Santo,", fr:"qui a été conçu du Saint-Esprit,", it:"che fu concepito di Spirito Santo,", de:"empfangen durch den Heiligen Geist,", pt:"que foi concebido pelo Espírito Santo,", pl:"który się począł z Ducha Świętego," },
    { en:"born of the Virgin Mary,", la:"natus ex Maria Virgine,", es:"nació de santa María Virgen,", fr:"est né de la Vierge Marie,", it:"nacque da Maria Vergine,", de:"geboren von der Jungfrau Maria,", pt:"nasceu da Virgem Maria,", pl:"narodził się z Maryi Dziewicy," },
    { en:"suffered under Pontius Pilate,", la:"passus sub Pontio Pilato,", es:"padeció bajo el poder de Poncio Pilato,", fr:"a souffert sous Ponce Pilate,", it:"patì sotto Ponzio Pilato,", de:"hat gelitten unter Pontius Pilatus,", pt:"padeceu sob Pôncio Pilatos,", pl:"umęczon pod Ponckim Piłatem," },
    { en:"was crucified, died, and was buried;", la:"crucifixus, mortuus, et sepultus,", es:"fue crucificado, muerto y sepultado,", fr:"a été crucifié, est mort, a été enseveli,", it:"fu crocifisso, morì e fu sepolto;", de:"wurde gekreuzigt, gestorben und begraben,", pt:"foi crucificado, morto e sepultado,", pl:"ukrzyżowan, umarł i pogrzebion," },
    { en:"he descended into hell;", la:"descendit ad infernos;", es:"descendió a los infiernos,", fr:"est descendu aux enfers;", it:"discese agli inferi;", de:"stieg hinab in das Reich des Todes;", pt:"desceu à mansão dos mortos;", pl:"zstąpił do piekieł," },
    { en:"on the third day he rose again from the dead;", la:"tertia die resurrexit a mortuis;", es:"al tercer día resucitó de entre los muertos,", fr:"le troisième jour est ressuscité des morts;", it:"il terzo giorno risorse dai morti;", de:"am dritten Tage auferstanden von den Toten;", pt:"ressuscitou ao terceiro dia,", pl:"trzeciego dnia zmartwychwstał;" },
    { en:"he ascended into heaven,", la:"ascendit ad caelos,", es:"subió a los cielos,", fr:"est monté aux cieux,", it:"salì al cielo,", de:"aufgefahren in den Himmel;", pt:"subiu aos céus,", pl:"wstąpił na niebiosa," },
    { en:"and is seated at the right hand of God the Father Almighty;", la:"sedet ad dexteram Dei Patris omnipotentis;", es:"y está sentado a la derecha de Dios, Padre todopoderoso.", fr:"est assis à la droite de Dieu le Père tout-puissant;", it:"siede alla destra di Dio Padre onnipotente;", de:"er sitzt zur Rechten Gottes, des allmächtigen Vaters;", pt:"está sentado à direita de Deus Pai todo-poderoso,", pl:"siedzi po prawicy Boga Ojca wszechmogącego," },
    { en:"from there he will come to judge the living and the dead.", la:"inde venturus est iudicare vivos et mortuos.", es:"desde allí ha de venir a juzgar a vivos y muertos.", fr:"il reviendra pour juger les vivants et les morts.", it:"di là verrà a giudicare i vivi e i morti.", de:"von dort wird er kommen, zu richten die Lebenden und die Toten.", pt:"e há-de vir julgar os vivos e os mortos.", pl:"stamtąd przyjdzie sądzić żywych i umarłych." },
    { en:"I believe in the Holy Spirit,", la:"Credo in Spiritum Sanctum,", es:"Creo en el Espíritu Santo,", fr:"Je crois en l'Esprit Saint,", it:"Credo nello Spirito Santo,", de:"Ich glaube an den Heiligen Geist,", pt:"Creio no Espírito Santo,", pl:"Wierzę w Ducha Świętego," },
    { en:"the holy catholic Church,", la:"sanctam Ecclesiam catholicam,", es:"la santa Iglesia católica,", fr:"en l'Église catholique,", it:"la santa Chiesa cattolica,", de:"die heilige christliche Kirche,", pt:"a santa Igreja Católica,", pl:"święty Kościół powszechny," },
    { en:"the communion of saints,", la:"sanctorum communionem,", es:"la comunión de los santos,", fr:"à la communion des saints,", it:"la comunione dei santi,", de:"Gemeinschaft der Heiligen,", pt:"a comunhão dos santos,", pl:"świętych obcowanie," },
    { en:"the forgiveness of sins,", la:"remissionem peccatorum,", es:"el perdón de los pecados,", fr:"à la rémission des péchés,", it:"la remissione dei peccati,", de:"Vergebung der Sünden,", pt:"a remissão dos pecados,", pl:"grzechów odpuszczenie," },
    { en:"the resurrection of the body,", la:"carnis resurrectionem,", es:"la resurrección de la carne,", fr:"à la résurrection de la chair,", it:"la risurrezione della carne,", de:"Auferstehung der Toten", pt:"a ressurreição da carne,", pl:"ciała zmartwychwstanie," },
    { en:"and life everlasting.", la:"vitam aeternam.", es:"y la vida eterna.", fr:"et à la vie éternelle.", it:"e la vita eterna.", de:"und das ewige Leben.", pt:"e a vida eterna.", pl:"życie wieczne." },
    { en:"Amen.", la:"Amen.", es:"Amén.", fr:"Amen.", it:"Amen.", de:"Amen.", pt:"Amém.", pl:"Amen." },
  ]
},

{
  id: 'niceneCreed',
  title: { en:"Nicene Creed", la:"Symbolum Nicaenum", es:"Credo Niceno", fr:"Symbole de Nicée", it:"Credo Niceno", de:"Nicänisches Glaubensbekenntnis", pt:"Credo Niceno", pl:"Wyznanie Wiary (Nicejskie)" },
  verses: [
    { en:"I believe in one God, the Father almighty,", la:"Credo in unum Deum, Patrem omnipotentem,", es:"Creo en un solo Dios, Padre todopoderoso,", fr:"Je crois en un seul Dieu, le Père tout-puissant,", it:"Credo in un solo Dio, Padre onnipotente,", de:"Ich glaube an den einen Gott, den Vater, den Allmächtigen,", pt:"Creio em um só Deus, Pai todo-poderoso,", pl:"Wierzę w jednego Boga, Ojca wszechmogącego," },
    { en:"maker of heaven and earth, of all things visible and invisible.", la:"factorem caeli et terrae, visibilium omnium et invisibilium.", es:"creador del cielo y de la tierra, de todo lo visible y lo invisible.", fr:"créateur du ciel et de la terre, de l'univers visible et invisible.", it:"creatore del cielo e della terra, di tutte le cose visibili e invisibili.", de:"des Schöpfers des Himmels und der Erde, aller sichtbaren und unsichtbaren Dinge.", pt:"criador do céu e da terra, de todas as coisas visíveis e invisíveis.", pl:"Stworzyciela nieba i ziemi, wszystkich rzeczy widzialnych i niewidzialnych." },
    { en:"I believe in one Lord Jesus Christ, the Only Begotten Son of God,", la:"Et in unum Dominum Iesum Christum, Filium Dei unigenitum,", es:"Creo en un solo Señor, Jesucristo, el Hijo único de Dios,", fr:"Je crois en un seul Seigneur, Jésus-Christ, le Fils unique de Dieu,", it:"Credo in un solo Signore, Gesù Cristo, unigenito Figlio di Dio,", de:"Und an den einen Herrn Jesus Christus, Gottes eingeborenen Sohn,", pt:"Creio em um só Senhor, Jesus Cristo, Filho Unigênito de Deus,", pl:"I w jednego Pana Jezusa Chrystusa, Syna Bożego Jednorodzonego," },
    { en:"born of the Father before all ages.", la:"et ex Patre natum ante omnia saecula.", es:"nacido del Padre antes de todos los siglos.", fr:"né du Père avant tous les siècles.", it:"nato dal Padre prima di tutti i secoli.", de:"aus dem Vater geboren vor aller Zeit.", pt:"nascido do Pai antes de todos os séculos.", pl:"który z Ojca jest zrodzony przed wszystkimi wiekami." },
    { en:"God from God, Light from Light, true God from true God,", la:"Deum de Deo, lumen de lumine, Deum verum de Deo vero,", es:"Dios de Dios, Luz de Luz, Dios verdadero de Dios verdadero,", fr:"Dieu de Dieu, Lumière de Lumière, vrai Dieu de vrai Dieu,", it:"Dio da Dio, Luce da Luce, Dio vero da Dio vero,", de:"Gott von Gott, Licht vom Licht, wahrer Gott vom wahren Gott,", pt:"Deus de Deus, Luz da Luz, Deus verdadeiro de Deus verdadeiro,", pl:"Boga z Boga, Światłość ze Światłości, Boga prawdziwego z Boga prawdziwego," },
    { en:"begotten, not made, consubstantial with the Father;", la:"genitum, non factum, consubstantialem Patri;", es:"engendrado, no creado, de la misma naturaleza del Padre;", fr:"engendré, non pas créé, consubstantiel au Père;", it:"generato, non creato, della stessa sostanza del Padre;", de:"gezeugt, nicht geschaffen, gleichen Wesens mit dem Vater;", pt:"gerado, não criado, consubstancial ao Pai;", pl:"zrodzonego a nie stworzonego, współistotnego Ojcu;" },
    { en:"through him all things were made.", la:"per quem omnia facta sunt.", es:"por quien todo fue hecho.", fr:"par lui tout a été fait.", it:"per mezzo di lui tutte le cose sono state create.", de:"durch ihn ist alles geschaffen.", pt:"por quem todas as coisas foram feitas.", pl:"a przez Niego wszystko się stało." },
    { en:"For us men and for our salvation he came down from heaven,", la:"Qui propter nos homines et propter nostram salutem descendit de caelis,", es:"Por nosotros los hombres y por nuestra salvación bajó del cielo,", fr:"Pour nous les hommes et pour notre salut il est descendu des cieux;", it:"Per noi uomini e per la nostra salvezza discese dal cielo;", de:"Er ist für uns Menschen und um unseres Heiles willen vom Himmel herabgestiegen", pt:"Por nós, homens, e para nossa salvação, desceu dos céus;", pl:"I dla nas ludzi i dla naszego zbawienia zstąpił z nieba." },
    { en:"and by the Holy Spirit was incarnate of the Virgin Mary, and became man.", la:"et incarnatus est de Spiritu Sancto ex Maria Virgine, et homo factus est.", es:"y por obra del Espíritu Santo se encarnó de María, la Virgen, y se hizo hombre.", fr:"il a pris chair de la Vierge Marie par l'Esprit-Saint, et s'est fait homme.", it:"e per opera dello Spirito Santo si è incarnato nel seno della Vergine Maria e si è fatto uomo.", de:"und hat Fleisch angenommen durch den Heiligen Geist von der Jungfrau Maria und ist Mensch geworden.", pt:"e se encarnou pelo Espírito Santo, no seio da Virgem Maria, e se fez homem.", pl:"I wcielił się z Ducha Świętego i z Maryi Dziewicy, i stał się człowiekiem." },
    { en:"For our sake he was crucified under Pontius Pilate;", la:"Crucifixus etiam pro nobis sub Pontio Pilato;", es:"Por nuestra causa fue crucificado en tiempos de Poncio Pilato;", fr:"Crucifié pour nous sous Ponce Pilate,", it:"Fu crocifisso per noi sotto Ponzio Pilato,", de:"Gekreuzigt wurde er sogar für uns unter Pontius Pilatus,", pt:"Foi crucificado por nós sob Pôncio Pilatos,", pl:"Ukrzyżowany również za nas, pod Ponckim Piłatem," },
    { en:"he suffered death and was buried,", la:"passus et sepultus est,", es:"padeció y fue sepultado,", fr:"il a souffert sa passion et a été mis au tombeau.", it:"morì e fu sepolto,", de:"hat gelitten und ist begraben worden;", pt:"padeceu e foi sepultado.", pl:"został umęczony i pogrzebany." },
    { en:"and rose again on the third day in accordance with the Scriptures.", la:"et resurrexit tertia die, secundum Scripturas,", es:"y resucitó al tercer día según las Escrituras,", fr:"Il est ressuscité le troisième jour, conformément aux Écritures.", it:"è risuscitato il terzo giorno, secondo le Scritture,", de:"ist am dritten Tage auferstanden nach der Schrift", pt:"ressuscitou ao terceiro dia, segundo as Escrituras,", pl:"I zmartwychwstał dnia trzeciego, jak oznajmia Pismo." },
    { en:"He ascended into heaven and is seated at the right hand of the Father.", la:"et ascendit in caelum, sedet ad dexteram Patris.", es:"subió al cielo y está sentado a la derecha del Padre.", fr:"Il est monté aux cieux; il est assis à la droite du Père.", it:"è salito al cielo, siede alla destra del Padre.", de:"ist aufgefahren in den Himmel und sitzet zur Rechten des Vaters.", pt:"subiu aos céus e está sentado à direita do Pai.", pl:"Wstąpił do nieba, siedzi po prawicy Ojca." },
    { en:"He will come again in glory to judge the living and the dead,", la:"et iterum venturus est cum gloria iudicare vivos et mortuos,", es:"y de nuevo vendrá con gloria para juzgar a vivos y muertos,", fr:"Il reviendra dans la gloire pour juger les vivants et les morts,", it:"e di nuovo verrà, nella gloria, per giudicare i vivi e i morti,", de:"und wird wiederkommen in Herrlichkeit, zu richten die Lebenden und die Toten,", pt:"e voltará em glória para julgar os vivos e os mortos;", pl:"I powtórnie przyjdzie w chwale sądzić żywych i umarłych," },
    { en:"and his kingdom will have no end.", la:"cuius regni non erit finis.", es:"y su reino no tendrá fin.", fr:"et son règne n'aura pas de fin.", it:"e il suo regno non avrà fine.", de:"und seiner Herrschaft wird kein Ende sein.", pt:"e o seu reino não terá fim.", pl:"a królestwu Jego nie będzie końca." },
    { en:"I believe in the Holy Spirit, the Lord, the giver of life,", la:"Et in Spiritum Sanctum, Dominum et vivificantem,", es:"Creo en el Espíritu Santo, Señor y dador de vida,", fr:"Je crois en l'Esprit-Saint, qui est Seigneur et qui donne la vie;", it:"Credo nello Spirito Santo, che è Signore e dà la vita,", de:"Ich glaube an den Heiligen Geist, der Herr ist und lebendig macht,", pt:"Creio no Espírito Santo, Senhor e Vivificador,", pl:"Wierzę w Ducha Świętego, Pana i Ożywiciela," },
    { en:"who proceeds from the Father and the Son,", la:"qui ex Patre Filioque procedit,", es:"que procede del Padre y del Hijo,", fr:"il procède du Père et du Fils;", it:"che procede dal Padre e dal Figlio;", de:"der vom Vater und vom Sohn ausgeht,", pt:"que procede do Pai e do Filho;", pl:"który od Ojca i Syna pochodzi," },
    { en:"who with the Father and the Son is adored and glorified,", la:"qui cum Patre et Filio simul adoratur et conglorificatur,", es:"que con el Padre y el Hijo recibe una misma adoración y gloria,", fr:"avec le Père et le Fils il reçoit même adoration et même gloire;", it:"che con il Padre e il Figlio è adorato e glorificato;", de:"der mit dem Vater und dem Sohn zugleich angebetet und verherrlicht wird,", pt:"que com o Pai e o Filho é adorado e glorificado;", pl:"który z Ojcem i Synem wspólnie odbiera uwielbienie i chwałę;" },
    { en:"who has spoken through the prophets.", la:"qui locutus est per prophetas.", es:"que habló por los profetas.", fr:"il a parlé par les prophètes.", it:"e che ha parlato per mezzo dei profeti.", de:"er hat gesprochen durch die Propheten.", pt:"que falou pelos profetas.", pl:"który mówił przez proroków." },
    { en:"I believe in one, holy, catholic and apostolic Church.", la:"Et unam, sanctam, catholicam et apostolicam Ecclesiam.", es:"Creo en la Iglesia, que es una, santa, católica y apostólica.", fr:"Je crois en l'Église, une, sainte, catholique et apostolique.", it:"Credo la Chiesa, una, santa, cattolica e apostolica.", de:"Ich glaube an die eine, heilige, katholische und apostolische Kirche.", pt:"Creio na Igreja, una, santa, católica e apostólica.", pl:"Wierzę w jeden, święty, powszechny i apostolski Kościół." },
    { en:"I confess one Baptism for the forgiveness of sins,", la:"Confiteor unum baptisma in remissionem peccatorum.", es:"Reconozco un solo bautismo para el perdón de los pecados.", fr:"Je reconnais un seul baptême pour la rémission des péchés.", it:"Professo un solo battesimo per il perdono dei peccati.", de:"Ich bekenne die eine Taufe zur Vergebung der Sünden.", pt:"Professo um só batismo para remissão dos pecados.", pl:"Uznaję jeden chrzest na odpuszczenie grzechów." },
    { en:"and I look forward to the resurrection of the dead", la:"et expecto resurrectionem mortuorum,", es:"espero la resurrección de los muertos", fr:"j'attends la résurrection des morts", it:"aspetto la risurrezione dei morti", de:"und erwarte die Auferstehung der Toten", pt:"e espero a ressurreição dos mortos", pl:"I oczekuję wskrzeszenia umarłych" },
    { en:"and the life of the world to come.", la:"et vitam venturi saeculi.", es:"y la vida del mundo futuro.", fr:"et la vie du monde à venir.", it:"e la vita del mondo che verrà.", de:"und das Leben der zukünftigen Welt.", pt:"e a vida do mundo que há-de vir.", pl:"i życia wiecznego w przyszłym świecie." },
    { en:"Amen.", la:"Amen.", es:"Amén.", fr:"Amen.", it:"Amen.", de:"Amen.", pt:"Amém.", pl:"Amen." },
  ]
},

// ─── HOLY MASS ───────────────────────────────────────────────

{
  id: 'confiteor',
  title: { en:"Confiteor", la:"Confiteor", es:"Yo Confieso", fr:"Je Confesse", it:"Confesso", de:"Ich Bekenne", pt:"Confesso a Deus", pl:"Spowiadam się" },
  verses: [
    { en:"I confess to almighty God", la:"Confiteor Deo omnipotenti", es:"Me confieso ante Dios todopoderoso", fr:"Je confesse à Dieu tout-puissant,", it:"Confesso a Dio onnipotente", de:"Ich bekenne Gott, dem Allmächtigen,", pt:"Confesso a Deus todo-poderoso", pl:"Spowiadam się Bogu wszechmogącemu" },
    { en:"and to you, my brothers and sisters,", la:"et vobis, fratres,", es:"y ante vosotros, hermanos,", fr:"je reconnais devant mes frères,", it:"e a voi, fratelli,", de:"und allen Schwestern und Brüdern,", pt:"e a vós, irmãos,", pl:"i wam, bracia i siostry," },
    { en:"that I have greatly sinned,", la:"quia peccavi nimis", es:"que he pecado mucho", fr:"que j'ai péché en pensée,", it:"che ho molto peccato", de:"dass ich Gutes unterlassen und Böses getan habe,", pt:"que pequei muitas vezes", pl:"że bardzo zgrzeszyłem" },
    { en:"in my thoughts and in my words,", la:"cogitatione, verbo,", es:"de pensamiento, palabra,", fr:"en parole, par action", it:"in pensieri, parole,", de:"ich habe gesündigt in Gedanken, Worten", pt:"por pensamentos e palavras,", pl:"myślą, mową," },
    { en:"in what I have done and in what I have failed to do,", la:"opere et omissione:", es:"obra y omisión.", fr:"et par omission.", it:"opere e omissioni,", de:"und Werken.", pt:"por atos e omissões.", pl:"uczynkiem i zaniedbaniem:" },
    { en:"through my fault, through my fault,", la:"mea culpa, mea culpa,", es:"por mi culpa, por mi culpa,", fr:"c'est ma faute, c'est ma faute,", it:"per mia colpa, mia colpa,", de:"durch meine Schuld, durch meine Schuld,", pt:"por minha culpa, minha culpa,", pl:"moja wina, moja wina," },
    { en:"through my most grievous fault.", la:"mea maxima culpa.", es:"por mi gran culpa.", fr:"c'est ma plus grande faute.", it:"mia grandissima colpa.", de:"durch meine große Schuld.", pt:"minha tão grande culpa.", pl:"moja bardzo wielka wina." },
    { en:"Therefore I ask blessed Mary ever-Virgin,", la:"Ideo precor beatam Mariam semper Virginem,", es:"Por eso ruego a santa María, siempre Virgen,", fr:"C'est pourquoi je supplie la Vierge Marie,", it:"E supplico la beata sempre Vergine Maria,", de:"Darum bitte ich die selige Jungfrau Maria,", pt:"Por isso, peço à Virgem Maria, sempre Virgem,", pl:"Przeto błagam Najświętszą Maryję Pannę," },
    { en:"all the Angels and Saints,", la:"omnes Angelos et Sanctos,", es:"a los ángeles, a los santos", fr:"les anges et tous les saints,", it:"gli angeli, i santi", de:"alle Engel und Heiligen", pt:"aos anjos e santos,", pl:"wszystkich Aniołów i Świętych" },
    { en:"and you, my brothers and sisters,", la:"et vos, fratres,", es:"y a vosotros, hermanos,", fr:"et vous aussi, mes frères,", it:"e voi, fratelli,", de:"und euch, Schwestern und Brüder,", pt:"e a vós, irmãos,", pl:"i was, bracia i siostry," },
    { en:"to pray for me to the Lord our God.", la:"orare pro me ad Dominum Deum nostrum.", es:"que intercedáis por mí ante Dios, nuestro Señor.", fr:"de prier pour moi le Seigneur notre Dieu.", it:"di pregare per me il Signore Dio nostro.", de:"für mich zu beten bei Gott, unserem Herrn.", pt:"que intercedais por mim junto ao Senhor nosso Deus.", pl:"o modlitwę za mnie do Pana Boga naszego." },
  ]
},

{
  id: 'kyrie',
  title: { en:"Kyrie Eleison", la:"Kyrie Eleison", es:"Señor Ten Piedad", fr:"Seigneur Prends Pitié", it:"Signore Pietà", de:"Herr Erbarme Dich", pt:"Senhor Tende Piedade", pl:"Panie Zmiłuj Się" },
  verses: [
    { en:"Lord, have mercy.", la:"Kyrie, eleison.", es:"Señor, ten piedad.", fr:"Seigneur, prends pitié.", it:"Signore, pietà.", de:"Herr, erbarme dich.", pt:"Senhor, tende piedade.", pl:"Panie, zmiłuj się." },
    { en:"Lord, have mercy.", la:"Kyrie, eleison.", es:"Señor, ten piedad.", fr:"Seigneur, prends pitié.", it:"Signore, pietà.", de:"Herr, erbarme dich.", pt:"Senhor, tende piedade.", pl:"Panie, zmiłuj się." },
    { en:"Lord, have mercy.", la:"Kyrie, eleison.", es:"Señor, ten piedad.", fr:"Seigneur, prends pitié.", it:"Signore, pietà.", de:"Herr, erbarme dich.", pt:"Senhor, tende piedade.", pl:"Panie, zmiłuj się." },
    { en:"Christ, have mercy.", la:"Christe, eleison.", es:"Cristo, ten piedad.", fr:"Christ, prends pitié.", it:"Cristo, pietà.", de:"Christus, erbarme dich.", pt:"Cristo, tende piedade.", pl:"Chryste, zmiłuj się." },
    { en:"Christ, have mercy.", la:"Christe, eleison.", es:"Cristo, ten piedad.", fr:"Christ, prends pitié.", it:"Cristo, pietà.", de:"Christus, erbarme dich.", pt:"Cristo, tende piedade.", pl:"Chryste, zmiłuj się." },
    { en:"Christ, have mercy.", la:"Christe, eleison.", es:"Cristo, ten piedad.", fr:"Christ, prends pitié.", it:"Cristo, pietà.", de:"Christus, erbarme dich.", pt:"Cristo, tende piedade.", pl:"Chryste, zmiłuj się." },
    { en:"Lord, have mercy.", la:"Kyrie, eleison.", es:"Señor, ten piedad.", fr:"Seigneur, prends pitié.", it:"Signore, pietà.", de:"Herr, erbarme dich.", pt:"Senhor, tende piedade.", pl:"Panie, zmiłuj się." },
    { en:"Lord, have mercy.", la:"Kyrie, eleison.", es:"Señor, ten piedad.", fr:"Seigneur, prends pitié.", it:"Signore, pietà.", de:"Herr, erbarme dich.", pt:"Senhor, tende piedade.", pl:"Panie, zmiłuj się." },
    { en:"Lord, have mercy.", la:"Kyrie, eleison.", es:"Señor, ten piedad.", fr:"Seigneur, prends pitié.", it:"Signore, pietà.", de:"Herr, erbarme dich.", pt:"Senhor, tende piedade.", pl:"Panie, zmiłuj się." },
  ]
},

{
  id: 'gloria',
  title: { en:"Gloria in Excelsis", la:"Gloria in Excelsis Deo", es:"Gloria en las Alturas", fr:"Gloire à Dieu", it:"Gloria a Dio", de:"Ehre sei Gott", pt:"Glória a Deus", pl:"Chwała Bogu" },
  verses: [
    { en:"Glory to God in the highest,", la:"Gloria in excelsis Deo,", es:"Gloria a Dios en el cielo,", fr:"Gloire à Dieu au plus haut des cieux,", it:"Gloria a Dio nell'alto dei cieli,", de:"Ehre sei Gott in der Höhe,", pt:"Glória a Deus nas alturas,", pl:"Chwała Bogu na wysokości," },
    { en:"and on earth peace to people of good will.", la:"et in terra pax hominibus bonae voluntatis.", es:"y en la tierra paz a los hombres que ama el Señor.", fr:"et paix sur la terre aux hommes qu'il aime.", it:"e pace in terra agli uomini di buona volontà.", de:"und Friede auf Erden den Menschen seiner Gnade.", pt:"e paz na terra aos homens por ele amados.", pl:"a na ziemi pokój ludziom dobrej woli." },
    { en:"We praise you, we bless you, we adore you, we glorify you,", la:"Laudamus te, benedicimus te, adoramus te, glorificamus te,", es:"Por tu inmensa gloria te alabamos, te bendecimos, te adoramos, te glorificamos,", fr:"Nous te louons, nous te bénissons, nous t'adorons, nous te glorifions,", it:"Noi ti lodiamo, ti benediciamo, ti adoriamo, ti glorifichiamo,", de:"Wir loben dich, wir preisen dich, wir beten dich an, wir rühmen dich,", pt:"Nós vos louvamos, vos bendizemos, vos adoramos, vos glorificamos,", pl:"Chwalimy Cię. Błogosławimy Cię. Wielbimy Cię. Wysławiamy Cię." },
    { en:"we give you thanks for your great glory,", la:"gratias agimus tibi propter magnam gloriam tuam,", es:"te damos gracias por tu inmensa gloria.", fr:"nous te rendons grâce pour ton immense gloire,", it:"ti rendiamo grazie per la tua gloria immensa,", de:"und danken dir, denn groß ist deine Herrlichkeit.", pt:"vos damos graças pela vossa imensa glória.", pl:"Dzięki Ci składamy, bo wielka jest chwała Twoja." },
    { en:"Lord God, heavenly King, O God, almighty Father.", la:"Domine Deus, Rex caelestis, Deus Pater omnipotens.", es:"Señor Dios, Rey celestial, Dios Padre todopoderoso.", fr:"Seigneur Dieu, Roi du ciel, Dieu le Père tout-puissant,", it:"Signore Dio, Re del cielo, Dio Padre onnipotente.", de:"Herr und Gott, König des Himmels, Gott und Vater, Herrscher über das All.", pt:"Senhor Deus, rei dos céus, Deus Pai todo-poderoso.", pl:"Panie Boże, Królu nieba, Boże Ojcze wszechmogący." },
    { en:"Lord Jesus Christ, Only Begotten Son,", la:"Domine Fili unigenite, Iesu Christe,", es:"Señor Jesucristo, Hijo único,", fr:"Seigneur, Fils unique, Jésus-Christ,", it:"Signore, Figlio unigenito, Gesù Cristo,", de:"Herr Jesus Christus, eingeborener Sohn,", pt:"Senhor Jesus Cristo, Filho Unigênito,", pl:"Panie Jezu Chryste, Synu Jednorodzony," },
    { en:"Lord God, Lamb of God, Son of the Father,", la:"Domine Deus, Agnus Dei, Filius Patris,", es:"Señor Dios, Cordero de Dios, Hijo del Padre,", fr:"Seigneur Dieu, Agneau de Dieu, le Fils du Père,", it:"Signore Dio, Agnello di Dio, Figlio del Padre,", de:"Herr und Gott, Lamm Gottes, Sohn des Vaters,", pt:"Senhor Deus, Cordeiro de Deus, Filho do Pai,", pl:"Panie Boże, Baranku Boży, Synu Ojca," },
    { en:"you take away the sins of the world, have mercy on us;", la:"qui tollis peccata mundi, miserere nobis;", es:"tú que quitas el pecado del mundo, ten piedad de nosotros;", fr:"toi qui enlèves le péché du monde, prends pitié de nous;", it:"tu che togli i peccati del mondo, abbi pietà di noi;", de:"du nimmst hinweg die Sünde der Welt: erbarme dich unser;", pt:"vós que tirais o pecado do mundo, tende piedade de nós;", pl:"który gładzisz grzechy świata, zmiłuj się nad nami;" },
    { en:"you take away the sins of the world, receive our prayer;", la:"qui tollis peccata mundi, suscipe deprecationem nostram;", es:"tú que quitas el pecado del mundo, atiende nuestra súplica;", fr:"toi qui enlèves le péché du monde, reçois notre prière;", it:"tu che togli i peccati del mondo, accogli la nostra supplica;", de:"du nimmst hinweg die Sünde der Welt: nimm unser Gebet an;", pt:"vós que tirais o pecado do mundo, atendei a nossa súplica;", pl:"który gładzisz grzechy świata, przyjm błaganie nasze;" },
    { en:"you are seated at the right hand of the Father, have mercy on us.", la:"qui sedes ad dexteram Patris, miserere nobis.", es:"tú que estás sentado a la derecha del Padre, ten piedad de nosotros.", fr:"toi qui es assis à la droite du Père, prends pitié de nous.", it:"tu che siedi alla destra del Padre, abbi pietà di noi.", de:"du sitzest zur Rechten des Vaters: erbarme dich unser.", pt:"vós que estais à direita do Pai, tende piedade de nós.", pl:"który siedzisz po prawicy Ojca, zmiłuj się nad nami." },
    { en:"For you alone are the Holy One, you alone are the Lord,", la:"Quoniam tu solus Sanctus, tu solus Dominus,", es:"Porque sólo tú eres Santo, sólo tú Señor,", fr:"Car toi seul es saint, toi seul es Seigneur,", it:"Perché tu solo il Santo, tu solo il Signore,", de:"Denn du allein bist der Heilige, du allein der Herr,", pt:"Pois só vós sois o Santo, só vós o Senhor,", pl:"Albowiem tylko Tyś jest Święty. Tylko Tyś jest Panem." },
    { en:"you alone are the Most High, Jesus Christ,", la:"tu solus Altissimus, Iesu Christe,", es:"sólo tú el Altísimo, Jesucristo,", fr:"toi seul le Très-Haut, Jésus-Christ,", it:"tu solo l'Altissimo, Gesù Cristo,", de:"du allein der Höchste, Jesus Christus,", pt:"só vós o Altíssimo, Jesus Cristo,", pl:"Tylko Tyś Najwyższy, Jezu Chryste," },
    { en:"with the Holy Spirit, in the glory of God the Father.", la:"cum Sancto Spiritu, in gloria Dei Patris.", es:"con el Espíritu Santo en la gloria de Dios Padre.", fr:"avec le Saint-Esprit dans la gloire de Dieu le Père.", it:"con lo Spirito Santo nella gloria di Dio Padre.", de:"mit dem Heiligen Geist, zur Ehre Gottes des Vaters.", pt:"com o Espírito Santo na glória de Deus Pai.", pl:"z Duchem Świętym w chwale Boga Ojca." },
    { en:"Amen.", la:"Amen.", es:"Amén.", fr:"Amen.", it:"Amen.", de:"Amen.", pt:"Amém.", pl:"Amen." },
  ]
},

{
  id: 'sanctus',
  title: { en:"Sanctus", la:"Sanctus", es:"Santo", fr:"Saint", it:"Santo", de:"Heilig", pt:"Santo", pl:"Święty" },
  verses: [
    { en:"Holy, Holy, Holy Lord God of hosts.", la:"Sanctus, Sanctus, Sanctus Dominus Deus Sabaoth.", es:"Santo, Santo, Santo es el Señor, Dios del universo.", fr:"Saint, Saint, Saint, le Seigneur, Dieu de l'univers.", it:"Santo, Santo, Santo il Signore Dio dell'universo.", de:"Heilig, Heilig, Heilig Gott, Herr aller Mächte und Gewalten.", pt:"Santo, Santo, Santo Senhor Deus do universo.", pl:"Święty, Święty, Święty Pan Bóg Zastępów." },
    { en:"Heaven and earth are full of your glory.", la:"Pleni sunt caeli et terra gloria tua.", es:"Llenos están el cielo y la tierra de tu gloria.", fr:"Le ciel et la terre sont remplis de ta gloire.", it:"I cieli e la terra sono pieni della tua gloria.", de:"Himmel und Erde sind erfüllt von deiner Herrlichkeit.", pt:"Os céus e a terra estão cheios da vossa glória.", pl:"Pełne są niebiosa i ziemia chwały Twojej." },
    { en:"Hosanna in the highest.", la:"Hosanna in excelsis.", es:"Hosanna en el cielo.", fr:"Hosanna au plus haut des cieux.", it:"Osanna nell'alto dei cieli.", de:"Hosanna in der Höhe.", pt:"Hosana nas alturas.", pl:"Hosanna na wysokości." },
    { en:"Blessed is he who comes in the name of the Lord.", la:"Benedictus qui venit in nomine Domini.", es:"Bendito el que viene en nombre del Señor.", fr:"Béni soit celui qui vient au nom du Seigneur.", it:"Benedetto colui che viene nel nome del Signore.", de:"Hochgelobt sei, der da kommt im Namen des Herrn.", pt:"Bendito o que vem em nome do Senhor.", pl:"Błogosławiony, który idzie w imię Pańskie." },
    { en:"Hosanna in the highest.", la:"Hosanna in excelsis.", es:"Hosanna en el cielo.", fr:"Hosanna au plus haut des cieux.", it:"Osanna nell'alto dei cieli.", de:"Hosanna in der Höhe.", pt:"Hosana nas alturas.", pl:"Hosanna na wysokości." },
  ]
},

{
  id: 'agnus',
  title: { en:"Agnus Dei", la:"Agnus Dei", es:"Cordero de Dios", fr:"Agneau de Dieu", it:"Agnello di Dio", de:"Lamm Gottes", pt:"Cordeiro de Deus", pl:"Baranku Boży" },
  verses: [
    { en:"Lamb of God, you take away the sins of the world,", la:"Agnus Dei, qui tollis peccata mundi,", es:"Cordero de Dios, que quitas el pecado del mundo,", fr:"Agneau de Dieu, qui enlèves le péché du monde,", it:"Agnello di Dio, che togli i peccati del mondo,", de:"Lamm Gottes, du nimmst hinweg die Sünde der Welt:", pt:"Cordeiro de Deus, que tirais os pecados do mundo,", pl:"Baranku Boży, który gładzisz grzechy świata," },
    { en:"have mercy on us.", la:"miserere nobis.", es:"ten piedad de nosotros.", fr:"prends pitié de nous.", it:"abbi pietà di noi.", de:"erbarme dich unser.", pt:"tende piedade de nós.", pl:"zmiłuj się nad nami." },
    { en:"Lamb of God, you take away the sins of the world,", la:"Agnus Dei, qui tollis peccata mundi,", es:"Cordero de Dios, que quitas el pecado del mundo,", fr:"Agneau de Dieu, qui enlèves le péché du monde,", it:"Agnello di Dio, che togli i peccati del mondo,", de:"Lamm Gottes, du nimmst hinweg die Sünde der Welt:", pt:"Cordeiro de Deus, que tirais os pecados do mundo,", pl:"Baranku Boży, który gładzisz grzechy świata," },
    { en:"have mercy on us.", la:"miserere nobis.", es:"ten piedad de nosotros.", fr:"prends pitié de nous.", it:"abbi pietà di noi.", de:"erbarme dich unser.", pt:"tende piedade de nós.", pl:"zmiłuj się nad nami." },
    { en:"Lamb of God, you take away the sins of the world,", la:"Agnus Dei, qui tollis peccata mundi,", es:"Cordero de Dios, que quitas el pecado del mundo,", fr:"Agneau de Dieu, qui enlèves le péché du monde,", it:"Agnello di Dio, che togli i peccati del mondo,", de:"Lamm Gottes, du nimmst hinweg die Sünde der Welt:", pt:"Cordeiro de Deus, que tirais os pecados do mundo,", pl:"Baranku Boży, który gładzisz grzechy świata," },
    { en:"grant us peace.", la:"dona nobis pacem.", es:"danos la paz.", fr:"donne-nous la paix.", it:"dona a noi la pace.", de:"gib uns deinen Frieden.", pt:"dai-nos a paz.", pl:"obdarz nas pokojem." },
  ]
},

// ─── MARIAN PRAYERS ─────────────────────────────────────────

{
  id: 'salveRegina',
  title: { en:"Salve Regina", la:"Salve Regina", es:"Dios te Salve Reina", fr:"Salut, ô Reine", it:"Salve Regina", de:"Sei gegrüßt, o Königin", pt:"Salve Rainha", pl:"Witaj Królowo" },
  verses: [
    { en:"Hail, Holy Queen, Mother of Mercy,", la:"Salve, Regina, Mater misericordiae,", es:"Dios te salve, Reina y Madre de misericordia,", fr:"Salut, ô Reine, Mère de miséricorde,", it:"Salve, Regina, Madre di misericordia,", de:"Sei gegrüßt, o Königin, Mutter der Barmherzigkeit,", pt:"Salve, Rainha, Mãe de misericórdia,", pl:"Witaj, Królowo, Matko miłosierdzia," },
    { en:"our life, our sweetness and our hope.", la:"vita, dulcedo, et spes nostra, salve.", es:"vida, dulzura y esperanza nuestra.", fr:"notre vie, notre douceur et notre espérance.", it:"vita, dolcezza e speranza nostra.", de:"unser Leben, unsere Wonne und unsere Hoffnung.", pt:"vida, doçura e esperança nossa.", pl:"życie, słodyczy i nadziejo nasza." },
    { en:"To thee do we cry, poor banished children of Eve;", la:"Ad te clamamus, exsules filii Hevae,", es:"A ti clamamos los desterrados hijos de Eva;", fr:"Vers toi nous crions, pauvres exilés enfants d'Ève;", it:"A te ricorriamo, esuli figli di Eva;", de:"Zu dir rufen wir verbannte Kinder Evas,", pt:"A vós bradamos os degredados filhos de Eva;", pl:"Do Ciebie wołamy wygnańcy, synowie Ewy;" },
    { en:"to thee do we send up our sighs,", la:"ad te suspiramus gementes et flentes", es:"a ti suspiramos gimiendo y llorando", fr:"vers toi nous soupirons gémissant et pleurant", it:"a te sospiriamo gementi e piangenti", de:"zu dir seufzen wir jammernd und weinend", pt:"a vós suspiramos gemendo e chorando", pl:"do Ciebie wzdychamy, jęcząc i płacząc" },
    { en:"in this valley of tears.", la:"in hac lacrimarum valle.", es:"en este valle de lágrimas.", fr:"dans cette vallée de larmes.", it:"in questa valle di lacrime.", de:"in diesem Tal der Tränen.", pt:"neste vale de lágrimas.", pl:"na tym łez padole." },
    { en:"Turn then, most gracious advocate,", la:"Eia ergo, advocata nostra,", es:"Ea, pues, Señora, abogada nuestra,", fr:"Tourne donc vers nous, ô la plus clémente,", it:"Orsù dunque, avvocata nostra,", de:"Wende denn, o Fürsprecherin,", pt:"Eia, pois, advogada nossa,", pl:"Przeto, Orędowniczko nasza," },
    { en:"thine eyes of mercy toward us;", la:"illos tuos misericordes oculos ad nos converte;", es:"vuelve a nosotros esos tus ojos misericordiosos;", fr:"tes regards de miséricorde vers nous;", it:"i tuoi occhi misericordiosi verso di noi;", de:"deine barmherzigen Augen uns zu.", pt:"esses vossos olhos misericordiosos para nós;", pl:"te swoje oczy miłosierdzia ku nam zwróć;" },
    { en:"and after this, our exile,", la:"et Iesum, benedictum fructum ventris tui,", es:"y después de este destierro,", fr:"et après cet exil,", it:"e dopo questo esilio,", de:"und nach diesem Jammertal", pt:"e depois deste exílio,", pl:"a po tym wygnaniu" },
    { en:"show unto us the blessed fruit of thy womb, Jesus.", la:"nobis post hoc exsilium ostende.", es:"muéstranos a Jesús, fruto bendito de tu vientre.", fr:"montre-nous Jésus, le fruit béni de tes entrailles.", it:"mostraci Gesù, il frutto benedetto del tuo seno.", de:"zeig uns Jesus, die gebenedeite Frucht deines Leibes.", pt:"mostrai-nos Jesus, o bendito fruto do vosso ventre.", pl:"ukaż nam Jezusa, błogosławiony owoc żywota Twojego." },
    { en:"O clement, O loving, O sweet Virgin Mary.", la:"O clemens, O pia, O dulcis Virgo Maria.", es:"Oh clemente, oh piadosa, oh dulce Virgen María.", fr:"Ô clémente, ô compatissante, ô douce Vierge Marie.", it:"O clemente, o pia, o dolce Vergine Maria.", de:"O gütige, o milde, o süße Jungfrau Maria.", pt:"Ó clemente, ó piedosa, ó doce Virgem Maria.", pl:"O łaskawa, o litościwa, o słodka Panno Maryjo." },
  ]
},

{
  id: 'reginaCaeli',
  title: { en:"Regina Caeli", la:"Regina Caeli", es:"Reina del Cielo", fr:"Reine du Ciel", it:"Regina del Cielo", de:"Himmelskönigin", pt:"Rainha do Céu", pl:"Królowo Nieba" },
  verses: [
    { en:"Queen of heaven, rejoice, alleluia:", la:"Regina caeli, laetare, alleluia:", es:"Alégrate, Reina del cielo, aleluya:", fr:"Reine du ciel, réjouis-toi, alléluia:", it:"Regina del cielo, rallegrati, alleluia:", de:"Himmelskönigin, freue dich, Halleluja:", pt:"Alegra-te, ó Rainha do céu, aleluia:", pl:"Królowo nieba, wesel się, alleluja:" },
    { en:"for he whom you merited to bear, alleluia,", la:"Quia quem meruisti portare, alleluia,", es:"porque aquel a quien mereciste llevar en tu seno, aleluya,", fr:"car celui que tu as mérité de porter, alléluia,", it:"perché colui che hai meritato di portare, alleluia,", de:"Denn wen du zu tragen würdig warst, Halleluja,", pt:"porque aquele que merecestes transportar, aleluia,", pl:"bo Ten, któregoś nosić zasłużyła, alleluja," },
    { en:"has risen as he said, alleluia.", la:"Resurrexit sicut dixit, alleluia.", es:"ha resucitado según prometió, aleluya.", fr:"est ressuscité comme il l'avait dit, alléluia.", it:"è risuscitato come aveva promesso, alleluia.", de:"ist auferstanden wie er gesagt hat, Halleluja.", pt:"ressuscitou como disse, aleluia.", pl:"zmartwychwstał, jak powiedział, alleluja." },
    { en:"Pray for us to God, alleluia.", la:"Ora pro nobis Deum, alleluia.", es:"Ruega a Dios por nosotros, aleluya.", fr:"Prie Dieu pour nous, alléluia.", it:"Prega Dio per noi, alleluia.", de:"Bitte für uns Gott, Halleluja.", pt:"Rogai por nós a Deus, aleluia.", pl:"Módl się za nami do Boga, alleluja." },
    { en:"Rejoice and be glad, O Virgin Mary, alleluia.", la:"Gaude et laetare, Virgo Maria, alleluia.", es:"Alégrate y gózate, Virgen María, aleluya.", fr:"Réjouis-toi et sois dans l'allégresse, Vierge Marie, alléluia.", it:"Rallegrati e gioisci, Vergine Maria, alleluia.", de:"Freue dich und juble, Jungfrau Maria, Halleluja.", pt:"Alegra-te e exulta, Virgem Maria, aleluia.", pl:"Raduj się i wesel, Panno Maryjo, alleluja." },
    { en:"For the Lord has truly risen, alleluia.", la:"Quia surrexit Dominus vere, alleluia.", es:"Porque el Señor ha resucitado de verdad, aleluya.", fr:"Car le Seigneur est vraiment ressuscité, alléluia.", it:"Perché il Signore è davvero risorto, alleluia.", de:"Denn der Herr ist wahrhaftig auferstanden, Halleluja.", pt:"Porque verdadeiramente ressuscitou o Senhor, aleluia.", pl:"Bo naprawdę zmartwychwstał Pan, alleluja." },
    { en:"Let us pray: O God, who through the resurrection of your Son,", la:"Oremus: Deus, qui per resurrectionem Filii tui,", es:"Oremos: Oh Dios, que por la resurrección de tu Hijo,", fr:"Prions: Ô Dieu qui, par la résurrection de votre Fils,", it:"Preghiamo: O Dio, che per la risurrezione del tuo Figlio,", de:"Lasset uns beten: O Gott, der du durch die Auferstehung deines Sohnes,", pt:"Oremos: Ó Deus, que pela Ressurreição do vosso Filho,", pl:"Módlmy się: Boże, który przez zmartwychwstanie Syna Twojego," },
    { en:"our Lord Jesus Christ, gave joy to the world,", la:"Domini nostri Iesu Christi, mundum laetificare dignatus es,", es:"nuestro Señor Jesucristo, llenaste el mundo de alegría,", fr:"notre Seigneur Jésus-Christ, as daigné réjouir le monde,", it:"il Signore nostro Gesù Cristo, si è degnato di rallegrare il mondo,", de:"unseres Herrn Jesus Christus, die Welt zu erfreuen geruhtest,", pt:"nosso Senhor Jesus Cristo, te dignaste alegrar o mundo,", pl:"Pana naszego Jezusa Chrystusa, uradowałeś świat," },
    { en:"grant that through his Mother, the Virgin Mary,", la:"praesta, quaesumus, ut per eius Genetricem Virginem Mariam,", es:"concede que por su Madre, la Virgen María,", fr:"accorde-nous, par l'intercession de sa Mère, la Vierge Marie,", it:"concedici, per la sua Madre, la Vergine Maria,", de:"gib, dass wir durch seine Mutter, die Jungfrau Maria,", pt:"concedei-nos, por intercessão de sua Mãe, a Virgem Maria,", pl:"spraw, abyśmy przez Jego Rodzicielkę, Maryję Dziewicę," },
    { en:"we may obtain the joys of everlasting life.", la:"perpetuae capiamus gaudia vitae.", es:"obtengamos las alegrías de la vida eterna.", fr:"les joies de la vie éternelle.", it:"la gioia della vita eterna.", de:"die Freuden des ewigen Lebens erlangen.", pt:"os gozos da vida eterna.", pl:"dostąpili radości życia wiecznego." },
    { en:"Through Christ our Lord. Amen.", la:"Per eundem Christum Dominum nostrum. Amen.", es:"Por el mismo Cristo nuestro Señor. Amén.", fr:"Par le même Jésus-Christ, notre Seigneur. Amen.", it:"Per lo stesso Cristo nostro Signore. Amen.", de:"Durch denselben Christus, unsern Herrn. Amen.", pt:"Por Cristo, nosso Senhor. Amém.", pl:"Przez Chrystusa, Pana naszego. Amen." },
  ]
},

{
  id: 'memorare',
  title: { en:"Memorare", la:"Memorare", es:"Acordaos", fr:"Memorare", it:"Memorare", de:"Memorare", pt:"Memorare", pl:"Memorare" },
  verses: [
    { en:"Remember, O most gracious Virgin Mary,", la:"Memorare, O piissima Virgo Maria,", es:"Acordaos, oh piadosísima Virgen María,", fr:"Souvenez-vous, ô très pieuse Vierge Marie,", it:"Ricordatevi, o piissima Vergine Maria,", de:"Gedenke, o gütigste Jungfrau Maria,", pt:"Lembrai-vos, ó puríssima Virgem Maria,", pl:"Pomnij, o Najłaskawsza Panno Maryjo," },
    { en:"that never was it known", la:"non esse auditum a saeculo,", es:"que jamás se ha sabido", fr:"qu'on n'a jamais entendu dire", it:"che non si è mai udito", de:"dass noch niemals gehört worden ist,", pt:"que nunca se ouviu dizer", pl:"że ktokolwiek uciekając się do Twej opieki," },
    { en:"that anyone who fled to thy protection,", la:"quemquam ad tua currentem praesidia,", es:"que ninguno que haya acudido a tu protección,", fr:"que quelqu'un qui ait eu recours à ta protection,", it:"che qualcuno che sia ricorso alla tua protezione,", de:"dass jemand, der zu deinem Schutz Zuflucht nahm,", pt:"que alguém que pediu vosso socorro,", pl:"błagając o Twą pomoc" },
    { en:"implored thy help, or sought thy intercession,", la:"tua implorantem auxilia, tua petentem suffragia,", es:"implorado tu asistencia o reclamado tu intercesión,", fr:"imploré ton assistance, réclamé ton intercession,", it:"implorato il tuo aiuto, chiesto la tua intercessione,", de:"deine Hilfe anrief oder deine Fürsprache suchte,", pt:"implorado o vosso auxílio ou pedido o vosso socorro,", pl:"i wstawiennictwa wzywając," },
    { en:"was left unaided.", la:"esse derelictum.", es:"haya sido desamparado.", fr:"ait été abandonné.", it:"sia stato abbandonato.", de:"ohne Hilfe geblieben wäre.", pt:"ficasse por Vós desamparado.", pl:"był opuszczony." },
    { en:"Inspired by this confidence,", la:"Ego tali animatus confidentia,", es:"Animado por esta confianza,", fr:"Animé d'une pareille confiance,", it:"Animato da questa fiducia,", de:"Von diesem Vertrauen beseelt,", pt:"Animado por esta confiança,", pl:"Ożywiony tą ufnością," },
    { en:"I fly unto thee, O Virgin of virgins, my Mother;", la:"ad te, Virgo virginum, Mater, curro,", es:"acudo a ti, oh Virgen de las vírgenes, Madre mía;", fr:"je vole vers toi, ô Vierge des vierges, ma Mère;", it:"ricorro a te, o Vergine delle vergini, mia Madre,", de:"eile ich zu dir, o Jungfrau der Jungfrauen, meine Mutter;", pt:"recorro a Vós, ó Virgem das virgens, minha Mãe;", pl:"biegnę do Ciebie, o Panno nad pannami, Matko moja;" },
    { en:"to thee do I come, before thee I stand, sinful and sorrowful.", la:"ad te venio, coram te gemens peccator assisto.", es:"a ti vengo, ante ti me postro, pecador arrepentido.", fr:"je viens vers toi, devant toi je me prosterne, pécheur repentant.", it:"vengo a te, davanti a te mi prostra, peccatore pentito.", de:"zu dir komme ich, vor dir stehe ich, sündig und reuevoll.", pt:"a Vós venho, ante Vós me apresento, pecador e angustiado.", pl:"do Ciebie przychodzę, przed Tobą stoję grzeszna i skruszona." },
    { en:"O Mother of the Word Incarnate, despise not my petitions,", la:"Noli, Mater Verbi, verba mea despicere;", es:"Oh Madre del Verbo Encarnado, no desprecies mis súplicas,", fr:"Ô Mère du Verbe incarné, ne méprise pas mes prières,", it:"O Madre del Verbo Incarnato, non disprezzare le mie suppliche,", de:"O Mutter des fleischgewordenen Wortes, verschmähe nicht mein Flehen,", pt:"Ó Mãe do Verbo Encarnado, não desprezeis as minhas súplicas,", pl:"O Matko Słowa Wcielonego, nie gardź prośbami moimi," },
    { en:"but in thy mercy hear and answer me.", la:"sed audi propitia et exaudi.", es:"sino escúchalas propicia y cúmplelas.", fr:"mais dans ta bonté écoute-les et exauce-les.", it:"ma ascoltale nella tua bontà ed esaudiscile.", de:"sondern erhöre mich gnädig und gewähre mein Gebet.", pt:"mas na vossa bondade escutai-as e atendei-as.", pl:"ale wysłuchaj je łaskawie i spełnij." },
    { en:"Amen.", la:"Amen.", es:"Amén.", fr:"Amen.", it:"Amen.", de:"Amen.", pt:"Amém.", pl:"Amen." },
  ]
},

{
  id: 'subTuum',
  title: { en:"Sub Tuum Praesidium", la:"Sub Tuum Praesidium", es:"Bajo tu Amparo", fr:"Sous ta Miséricorde", it:"Sotto la tua Protezione", de:"Unter deinen Schutz", pt:"Sob vossa proteção", pl:"Pod Twoją Obronę" },
  verses: [
    { en:"We fly to thy patronage,", la:"Sub tuum praesidium confugimus,", es:"Bajo tu amparo nos acogemos,", fr:"Sous ta miséricorde nous nous réfugions,", it:"Sotto la tua protezione cerchiamo rifugio,", de:"Unter deinen Schutz und Schirm fliehen wir,", pt:"Sob vossa proteção nos refugiamos,", pl:"Pod Twoją obronę uciekamy się," },
    { en:"O holy Mother of God;", la:"Sancta Dei Genetrix;", es:"santa Madre de Dios;", fr:"sainte Mère de Dieu;", it:"santa Madre di Dio;", de:"heilige Gottesmutter;", pt:"ó santa Mãe de Deus;", pl:"Święta Boża Rodzicielko;" },
    { en:"despise not our petitions in our necessities,", la:"nostras deprecationes ne despicias in necessitatibus,", es:"no deseches las súplicas que te dirigimos en nuestras necesidades,", fr:"ne rejette pas nos prières quand nous sommes dans l'épreuve,", it:"non disprezzare le nostre suppliche nelle avversità,", de:"verschmähe nicht unser Bitten in unserer Not,", pt:"não desprezeis as nossas súplicas nas nossas necessidades,", pl:"naszymi prośbami w potrzebach naszych nie gardź," },
    { en:"but deliver us always from all dangers,", la:"sed a periculis cunctis libera nos semper,", es:"antes bien líbranos de todos los peligros,", fr:"mais de tous les dangers délivre-nous toujours,", it:"ma liberaci da tutti i pericoli,", de:"sondern erlöse uns von aller Gefahr,", pt:"mas livrai-nos de todos os perigos,", pl:"ale nas od wszelkich złych przygód racz nieustannie wybawiać," },
    { en:"O glorious and blessed Virgin.", la:"Virgo gloriosa et benedicta.", es:"oh Virgen gloriosa y bendita.", fr:"ô Vierge glorieuse et bénie.", it:"o Vergine gloriosa e benedetta.", de:"du herrliche und hochgelobte Jungfrau.", pt:"ó Virgem gloriosa e bendita.", pl:"Panno chwalebna i błogosławiona." },
  ]
},

// ─── DEVOTIONAL ─────────────────────────────────────────────

{
  id: 'animaChristi',
  title: { en:"Anima Christi", la:"Anima Christi", es:"Alma de Cristo", fr:"Âme du Christ", it:"Anima di Cristo", de:"Seele Christi", pt:"Alma de Cristo", pl:"Duszo Chrystusowa" },
  verses: [
    { en:"Soul of Christ, sanctify me.", la:"Anima Christi, sanctifica me.", es:"Alma de Cristo, santifícame.", fr:"Âme du Christ, sanctifie-moi.", it:"Anima di Cristo, santificami.", de:"Seele Christi, heilige mich.", pt:"Alma de Cristo, santificai-me.", pl:"Duszo Chrystusowa, uświęć mnie." },
    { en:"Body of Christ, save me.", la:"Corpus Christi, salva me.", es:"Cuerpo de Cristo, sálvame.", fr:"Corps du Christ, sauve-moi.", it:"Corpo di Cristo, salvami.", de:"Leib Christi, rette mich.", pt:"Corpo de Cristo, salvai-me.", pl:"Ciało Chrystusowe, zbaw mnie." },
    { en:"Blood of Christ, inebriate me.", la:"Sanguis Christi, inebria me.", es:"Sangre de Cristo, embriágame.", fr:"Sang du Christ, enivre-moi.", it:"Sangue di Cristo, inebriami.", de:"Blut Christi, tränke mich.", pt:"Sangue de Cristo, embriagai-me.", pl:"Krwi Chrystusowa, napój mnie." },
    { en:"Water from the side of Christ, wash me.", la:"Aqua lateris Christi, lava me.", es:"Agua del costado de Cristo, lávame.", fr:"Eau du côté du Christ, lave-moi.", it:"Acqua del costato di Cristo, lavami.", de:"Wasser aus der Seite Christi, wasche mich.", pt:"Água do lado de Cristo, lavai-me.", pl:"Wodo boku Chrystusowego, obmyj mnie." },
    { en:"Passion of Christ, strengthen me.", la:"Passio Christi, conforta me.", es:"Pasión de Cristo, confórtame.", fr:"Passion du Christ, fortifie-moi.", it:"Passione di Cristo, confortami.", de:"Leiden Christi, stärke mich.", pt:"Paixão de Cristo, confortai-me.", pl:"Męko Chrystusowa, wzmocnij mnie." },
    { en:"O good Jesus, hear me.", la:"O bone Iesu, exaudi me.", es:"Oh, buen Jesús, óyeme.", fr:"Ô bon Jésus, exauce-moi.", it:"O buon Gesù, esaudiscimi.", de:"O guter Jesus, erhöre mich.", pt:"Ó bom Jesus, escutai-me.", pl:"O dobry Jezu, wysłuchaj mnie." },
    { en:"Within thy wounds hide me.", la:"Intra tua vulnera absconde me.", es:"Dentro de tus llagas, escóndeme.", fr:"Dans tes plaies, cache-moi.", it:"Nelle tue piaghe nascondimi.", de:"In deinen Wunden birg mich.", pt:"Dentro das vossas chagas, escondei-me.", pl:"W ranach swoich ukryj mnie." },
    { en:"Suffer me not to be separated from thee.", la:"Ne permittas me separari a te.", es:"No permitas que me aparte de ti.", fr:"Permets que je ne me sépare jamais de toi.", it:"Non permettere che mi separi da te.", de:"Lass mich nicht von dir getrennt werden.", pt:"Não permitais que eu Me separe de Vós.", pl:"Nie dopuść mi oddalić się od Ciebie." },
    { en:"From the malicious enemy, defend me.", la:"Ab hoste maligno defende me.", es:"Del maligno enemigo, defiéndeme.", fr:"De l'ennemi malin, défends-moi.", it:"Dal maligno nemico, difendimi.", de:"Vom bösen Feind beschütze mich.", pt:"Do inimigo maligno, defendei-me.", pl:"Od złośliwego nieprzyjaciela broń mnie." },
    { en:"In the hour of my death, call me,", la:"In hora mortis meae voca me,", es:"En la hora de mi muerte, llámame,", fr:"A l'heure de ma mort, appelle-moi,", it:"Nell'ora della mia morte chiamami,", de:"In der Stunde meines Todes rufe mich,", pt:"Na hora da minha morte, chamai-me,", pl:"W godzinę śmierci mojej wezwij mnie," },
    { en:"and bid me come unto thee,", la:"et iube me venire ad te,", es:"y mándame ir a ti,", fr:"et ordonne-moi de venir à toi,", it:"e comandami di venire a te,", de:"und gebiete mir, zu dir zu kommen,", pt:"e mandai-me ir a Vós,", pl:"i każ mi przyjść do siebie," },
    { en:"that with thy saints I may praise thee", la:"ut cum Sanctis tuis laudem te", es:"para que con tus santos te alabe", fr:"afin qu'avec tes saints je te loue", it:"perché con i tuoi santi ti possa lodare", de:"damit ich mit deinen Heiligen dich lobe", pt:"para que com os vossos santos vos louve", pl:"abym z Twoimi świętymi chwalił Ciebie" },
    { en:"forever and ever. Amen.", la:"in saecula saeculorum. Amen.", es:"por los siglos de los siglos. Amén.", fr:"dans les siècles des siècles. Amen.", it:"nei secoli dei secoli. Amen.", de:"in alle Ewigkeit. Amen.", pt:"pelos séculos dos séculos. Amém.", pl:"na wieki wieków. Amen." },
  ]
},

{
  id: 'angelus',
  title: { en:"Angelus", la:"Angelus Domini", es:"El Ángel del Señor", fr:"L'Angélus", it:"L'Angelus", de:"Der Engel des Herrn", pt:"O Ângelus", pl:"Anioł Pański" },
  verses: [
    { en:"V. The Angel of the Lord declared unto Mary:", la:"V. Angelus Domini nuntiavit Mariae:", es:"V. El ángel del Señor anunció a María:", fr:"V. L'Ange du Seigneur annonça à Marie:", it:"V. L'Angelo del Signore portò l'annuncio a Maria:", de:"V. Der Engel des Herrn brachte Maria die Botschaft,", pt:"V. O anjo do Senhor anunciou a Maria:", pl:"V. Anioł Pański zwiastował Pannie Maryi," },
    { en:"R. And she conceived of the Holy Spirit.", la:"R. Et concepit de Spiritu Sancto.", es:"R. Y concibió por obra del Espíritu Santo.", fr:"R. Et elle conçut du Saint-Esprit.", it:"R. Ed ella concepì per opera dello Spirito Santo.", de:"R. Und sie empfing vom Heiligen Geist.", pt:"R. E ela concebeu pelo Espírito Santo.", pl:"R. I poczęła z Ducha Świętego." },
    { en:"(Hail Mary...)", la:"(Ave Maria...)", es:"(Dios te salve...)", fr:"(Je vous salue Marie...)", it:"(Ave Maria...)", de:"(Gegrüßet seist du...)", pt:"(Ave Maria...)", pl:"(Zdrowaś Maryjo...)" },
    { en:"V. Behold the handmaid of the Lord:", la:"V. Ecce ancilla Domini:", es:"V. He aquí la esclava del Señor:", fr:"V. Voici la servante du Seigneur:", it:"V. Eccola la serva del Signore:", de:"V. Ich bin die Magd des Herrn:", pt:"V. Eis aqui a serva do Senhor:", pl:"V. Oto ja, służebnica Pańska:" },
    { en:"R. Be it done unto me according to thy word.", la:"R. Fiat mihi secundum verbum tuum.", es:"R. Hágase en mí según tu palabra.", fr:"R. Qu'il me soit fait selon ta parole.", it:"R. Sia fatto in me secondo la tua parola.", de:"R. Mir geschehe nach deinem Wort.", pt:"R. Faça-se em mim segundo a vossa palavra.", pl:"R. Niech mi się stanie według słowa Twego." },
    { en:"(Hail Mary...)", la:"(Ave Maria...)", es:"(Dios te salve...)", fr:"(Je vous salue Marie...)", it:"(Ave Maria...)", de:"(Gegrüßet seist du...)", pt:"(Ave Maria...)", pl:"(Zdrowaś Maryjo...)" },
    { en:"V. And the Word was made flesh:", la:"V. Et Verbum caro factum est:", es:"V. Y el Verbo se hizo carne:", fr:"V. Et le Verbe s'est fait chair:", it:"V. E il Verbo si fece carne:", de:"V. Und das Wort ist Fleisch geworden:", pt:"V. E o Verbo se fez carne:", pl:"V. A Słowo stało się ciałem," },
    { en:"R. And dwelt among us.", la:"R. Et habitavit in nobis.", es:"R. Y habitó entre nosotros.", fr:"R. Et il a habité parmi nous.", it:"R. E abitò in mezzo a noi.", de:"R. Und hat unter uns gewohnt.", pt:"R. E habitou entre nós.", pl:"R. I zamieszkało między nami." },
    { en:"(Hail Mary...)", la:"(Ave Maria...)", es:"(Dios te salve...)", fr:"(Je vous salue Marie...)", it:"(Ave Maria...)", de:"(Gegrüßet seist du...)", pt:"(Ave Maria...)", pl:"(Zdrowaś Maryjo...)" },
    { en:"V. Pray for us, O holy Mother of God.", la:"V. Ora pro nobis, Sancta Dei Genetrix.", es:"V. Ruega por nosotros, santa Madre de Dios.", fr:"V. Priez pour nous, sainte Mère de Dieu.", it:"V. Prega per noi, santa Madre di Dio.", de:"V. Bitte für uns, heilige Gottesmutter.", pt:"V. Rogai por nós, santa Mãe de Deus.", pl:"V. Módl się za nami, święta Boża Rodzicielko." },
    { en:"R. That we may be made worthy of the promises of Christ.", la:"R. Ut digni efficiamur promissionibus Christi.", es:"R. Para que seamos dignos de alcanzar las promesas de Jesucristo.", fr:"R. Afin que nous devenions dignes des promesses de Jésus-Christ.", it:"R. Per essere resi degni delle promesse di Cristo.", de:"R. Dass wir würdig werden der Verheißungen Christi.", pt:"R. A fim de que nos tornemos dignos das promessas de Cristo.", pl:"R. Abyśmy się stali godnymi obietnic Chrystusa Pana." },
    { en:"Let us pray: Pour forth, we beseech thee, O Lord, thy grace into our hearts,", la:"Oremus: Gratiam tuam, quaesumus Domine, mentibus nostris infunde,", es:"Oremos: Infunde, Señor, tu gracia en nuestras almas,", fr:"Prions: Répands, Seigneur, ta grâce dans nos cœurs,", it:"Preghiamo: Effondi, Signore, la tua grazia nei nostri cuori,", de:"Lasst uns beten: Gieß, o Herr, deine Gnade in unsere Herzen,", pt:"Oremos: Derramai, Senhor, a vossa graça em nossas almas,", pl:"Módlmy się: Łaskę swoją racz wlać w serca nasze, Panie," },
    { en:"that we, to whom the Incarnation of Christ thy Son was made known by the message of an Angel,", la:"ut qui, Angelo nuntiante, Christi Filii tui Incarnationem cognovimus,", es:"para que quienes hemos conocido la Encarnación de Cristo, tu Hijo, por el mensaje del Ángel,", fr:"afin que nous qui avons connu, par le message de l'Ange, l'Incarnation du Christ, ton Fils,", it:"affinché noi, che per l'annuncio dell'Angelo abbiamo conosciuto l'Incarnazione di Cristo tuo Figlio,", de:"damit wir, die wir durch die Botschaft des Engels die Menschwerdung Christi, deines Sohnes, erkannt haben,", pt:"para que nós, que pela mensagem do Anjo conhecemos a Encarnação de Cristo vosso Filho,", pl:"abyśmy, którzy przez zwiastowanie anielskie poznali Wcielenie Chrystusa Syna Twojego," },
    { en:"may by his Passion and Cross be brought to the glory of his Resurrection.", la:"per Passionem eius et Crucem ad resurrectionis gloriam perducamur.", es:"lleguemos por su Pasión y Cruz a la gloria de su Resurrección.", fr:"parvenions par sa Passion et sa Croix à la gloire de la Résurrection.", it:"per la sua Passione e Croce siamo portati alla gloria della Resurrezione.", de:"durch sein Leiden und sein Kreuz zur Herrlichkeit seiner Auferstehung geführt werden.", pt:"pela sua Paixão e Cruz sejamos conduzidos à glória da Ressurreição.", pl:"przez Mękę Jego i Krzyż byli doprowadzeni do chwały Zmartwychwstania." },
    { en:"Through the same Christ our Lord. Amen.", la:"Per eundem Christum Dominum nostrum. Amen.", es:"Por el mismo Jesucristo nuestro Señor. Amén.", fr:"Par le même Jésus-Christ, notre Seigneur. Amen.", it:"Per lo stesso Cristo nostro Signore. Amen.", de:"Durch denselben Christus, unsern Herrn. Amen.", pt:"Por Cristo, nosso Senhor. Amém.", pl:"Przez Chrystusa, Pana naszego. Amen." },
  ]
},

{
  id: 'actContrition',
  title: { en:"Act of Contrition", la:"Actus Contritionis", es:"Acto de Contrición", fr:"Acte de Contrition", it:"Atto di Contrizione", de:"Akt der Reue", pt:"Ato de Contrição", pl:"Akt Żalu" },
  verses: [
    { en:"O my God, I am heartily sorry for having offended thee,", la:"Deus meus, ex toto corde paenitet me omnium meorum peccatorum,", es:"Dios mío, me arrepiento de todo corazón de todos mis pecados,", fr:"Mon Dieu, je regrette d'avoir péché,", it:"Mio Dio, mi pento e mi dolgo con tutto il cuore dei miei peccati,", de:"Mein Gott, von ganzem Herzen bereue ich,", pt:"Meu Deus, arrependo-me de todo o coração de todos os meus pecados,", pl:"Boże mój, żałuję z całego serca za grzechy moje," },
    { en:"and I detest all my sins,", la:"eaque detestor,", es:"y los detesto con toda mi alma,", fr:"parce que j'ai péché contre toi,", it:"perché peccando ho meritato le tue pene,", de:"dass ich dich, meinen Gott, beleidigt habe,", pt:"detesto-os e os tenho em grande ódio,", pl:"nad nimi się obrzydzam," },
    { en:"because of thy just punishments,", la:"quia peccando, non solum poenas a te iuste statutas promeritus sum,", es:"que me has impuesto justamente,", fr:"mais surtout parce que tu es infiniment bon", it:"e molto più perché ho offeso te,", de:"nicht nur weil du mich gerecht bestrafen kannst,", pt:"porque com eles mereci as penas eternas,", pl:"bo przez nie zasłużyłem na Twoje sprawiedliwe kary," },
    { en:"but most of all because they offend thee, my God,", la:"sed praesertim quia offendi te, summum bonum,", es:"pero más aún porque te ofendo a ti, sumo bien,", fr:"et que le péché te déplaît.", it:"sommo bene, e degno di essere amato sopra ogni cosa.", de:"sondern weil ich dir, meinem Gott, Böses getan habe.", pt:"mas principalmente porque vos ofendi a Vós, sumo bem,", pl:"a nade wszystko dlatego, że Ciebie, najwyższe dobro," },
    { en:"who art all good and deserving of all my love.", la:"ac dignum qui super omnia diligaris.", es:"que mereces todo mi amor.", fr:"", it:"", de:"", pt:"que sois digno de todo o meu amor.", pl:"i Ojca mego najlitościwszego przez grzechy moje obraziłem." },
    { en:"I firmly resolve with the help of thy grace,", la:"Ideo firmiter propono, adiuvante gratia tua,", es:"Propongo firmemente con la ayuda de tu gracia,", fr:"Je prends la résolution, avec le secours de ta grâce,", it:"Propongo fermamente, con l'aiuto della tua grazia,", de:"Ich nehme mir fest vor, mit deiner Gnadenhilfe,", pt:"Firme-me proponho, com o auxílio da vossa graça,", pl:"Postanawiam mocno, przy łasce Bożej," },
    { en:"to sin no more and to avoid the near occasion of sin.", la:"de cetero me non peccaturum peccandique occasiones proximas fugiturum.", es:"de no pecar más y de huir las ocasiones de pecado.", fr:"de ne plus pécher et d'éviter les occasions de péché.", it:"di non peccare più e di fuggire le occasioni di peccato.", de:"nicht mehr zu sündigen und die Gelegenheiten zur Sünde zu meiden.", pt:"nunca mais pecar e evitar as ocasiões de pecado.", pl:"więcej nie grzeszyć i unikać okazji do grzechu." },
    { en:"Amen.", la:"Amen.", es:"Amén.", fr:"Amen.", it:"Amen.", de:"Amen.", pt:"Amém.", pl:"Amen." },
  ]
},

]; // end PRAYERS
